### ISSUE TITLE
Error selecting mp3

### ISSUE THREAD

**Issue by jalbrink** [athombv/com.athom.soundboard#13]
Using the MP3 from this blog https://blog.athom.com/dingen-die-je-kunt-doen-met-een-deurbel/?lang=nl
(Doorbell.mp3) I get a popup "error" after selecting the file. Both on 2.0.3 and 2.0.4beta

I am using homey2 firmware/app

![error](https://user-images.githubusercontent.com/45916953/51625049-82889a00-1f3c-11e9-865e-1f676d362682.jpg)

**Comment by WeeJeWel** [comment]
![img_2655](https://user-images.githubusercontent.com/319873/51537146-0e6fc880-1e4e-11e9-8af0-e51dc2d02f56.png)

I cannot reproduce the issue. What phone are you using? Does it work on https://developer.athom.com/tools/app-settings?

**Comment by jalbrink** [comment]
It's also not working using developer.athom.com on my desktop. My phone is
a oneplus6

**Comment by WeeJeWel** [comment]
Can you make a screencast of the error occuring?

**Comment by jalbrink** [comment]
Is a picture ok? :)

**Comment by WeeJeWel** [comment]
Sure!

**Comment by MrWriter87** [comment]
I have the same issue since homey v2. I cannot upload any wav or mp3 files that I used before. The error I get is invalid_type. Tried it with the doorbell mp3 as well.

**Comment by jalbrink** [comment]
Did you get the screenshot by the way? I sent it via email but it doesn't show here.
@MrWriter87 have you tried 2.0.4beta as well?

**Comment by WeeJeWel** [comment]
I've updated v2.0.5 to show the type in the `invalid_type` error. Can you guys try again and share the error message with me?

**Comment by jalbrink** [comment]
Uninstalled beta, then installed 2.0.5. Still get the popup that just says "error"

**Comment by WeeJeWel** [comment]
@jalbrink Still waiting on your picture.

**Comment by jalbrink** [comment]
tried to attach it in the mail but it failed apparently
![error](https://user-images.githubusercontent.com/45916953/51598933-da081500-1efe-11e9-846f-223a03b7ef0e.jpg)

**Comment by WeeJeWel** [comment]
@jalbrink Can you attach the file here in the issue?

**Comment by off112a** [comment]
Hi,

I have the same problem. See screenshot.

![img_1455](https://user-images.githubusercontent.com/22722009/51692597-90eaba80-1ffd-11e9-8879-82321366dd3f.PNG)

**Comment by Inversion-NL** [comment]
Same on Android
![screenshot_20190125-095831](https://user-images.githubusercontent.com/15921016/51735557-fbe0d380-2087-11e9-92a2-d676b36d2b11.png)

Attached the file

[Ding-dong-doorbell-rings.zip](https://github.com/athombv/com.athom.soundboard/files/2795357/Ding-dong-doorbell-rings.zip)

**Comment by MrWriter87** [comment]
@WeeJeWel I tried with beta and now the latest version as well. Still getting the same error as before without additional information.

**Comment by jalbrink** [comment]
Any status update?

**Comment by jalbrink** [comment]
For me it's fixed after the latest firmware and (mobile) app update.

**Comment by WeeJeWel** [comment]
This should be solved now.

**Comment by MrWriter87** [comment]
I still get the same error, I already reinstalled the app but it is not working for me :(

In the meanwhile I managed to upload a new mp3 but all old mp3's that have been used before are still giving errors. Also the doorbell from the athom site gives the same error

**Comment by Inversion-NL** [comment]
Works for me
